"""creating  tables

Revision ID: ea4c2d962967
Revises: 61b30f8b2dd7
Create Date: 2023-02-18 13:58:16.684478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4c2d962967'
down_revision = '61b30f8b2dd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
